import "../globals.css";
import type {Metadata} from "next";
import {Providers} from "@/app/providers";
import React from "react";

export const metadata: Metadata = {
    title: "Login Page",
    description: "Generated by create next app",
};

export default async function LoginLayout({children}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={`flex items-center justify-center flex-col`}>
        <Providers>
            {children}
        </Providers>
        </body>
        </html>
    );
}