export const languages: { [key: string]: string } = {
  "html": "html",
  "markup": "markup",
  "xml": "xml",
  "ssml": "ssml",
  "svg": "svg",
  "mathml": "mathml",
  "atom": "atom",
  "rss": "rss",
  "css": "css",
  "clike": "clike",
  "js": "javascript",
  "abap": "abap",
  "abnf": "abnf",
};
