import "./globals.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {Providers} from "@/app/providers";
import React from "react";
import Navbar from "@/components/navbar"
const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Home Page",
    description: "Generated by create next app",
};

export default async function RootLayout({children, modal}: {
    children: React.ReactNode;
    modal: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`flex items-center justify-center flex-col`}>
            <Providers>
                <Navbar />
                {children}
                {modal}
            </Providers>
            </body>
        </html>
    );
}