import "../globals.css";
import type {Metadata} from "next";
import {Providers} from "@/app/providers";
import React from "react";
import Navbar from "@/components/navbar"

export const metadata: Metadata = {
    title: "Home Page",
    description: "Generated by create next app",
};

export default async function HomeLayout({children}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`flex items-center justify-center flex-col`}>
            <Providers>
                <Navbar />
                {children}
            </Providers>
            </body>
        </html>
    );
}