import "../globals.css";
import type {Metadata} from "next";
import {Providers} from "@/app/providers";
import React from "react";
import Navbar from "@/components/navbar"
import {Session} from "next-auth";
import {prisma} from "@/lib/prisma";
import {getServerSession} from "next-auth/next";
import {options} from "@/app/api/auth/[...nextauth]/options";
import {NextResponse} from "next/server";

export const metadata: Metadata = {
    title: "Home Page",
    description: "Generated by create next app",
};

async function fetchSettings(session: Session) {
    return await prisma.setting.findMany({
        where: {
            userId: session?.user?.id,
        },
    })
}

export default async function HomeLayout({children}: {
    children: React.ReactNode;
}) {
    const session = await getServerSession(options)
    if (!session) {
        return NextResponse.json({message: "Not authorized!"}, {status: 401});
    }
    const settings = await fetchSettings(session)

    return (
        <html lang="en">
        <body className={`flex items-center justify-center flex-col`}
            // uncomment below line to use custom font for the whole app
            // style={{fontFamily:settings[0]?.fontFamily||"", fontSize: settings[0]?.fontSize||14+"px", fontWeight:settings[0]?.fontWeight||"600"}}
        >
        <Providers>
            <Navbar settings={settings[0]}/>
            {children}
        </Providers>
        </body>
        </html>
    );
}